### ISSUE TITLE
Lack of business line and store creation step

### ISSUE THREAD

**Issue by delonzhou** [adyen-examples/adyen-afp-sample#90]
Hi, 

I went through the whole onboarding process and found that the legal entity is not successfully verified because of lack of business line.

BTW, according to the doc at https://docs.adyen.com/platforms/onboard-users/onboarding-steps/?location=au&legal_entity=organization#create-store. creating business line and store are necessary steps. Could you please make the sample completely matched with the doc.

Thanks and best regards,
Denglong.

**Comment by gcatanese** [comment]
Thank you for reporting this, the step is indeed missing. We will plan an update to address it.
